#!/bin/bash

username=${1:-"test"}
password=${2:-"test"}

curl -X POST \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "erase-cookie=false&password=$password&popup=false&username=$username" \
    "https://login.aut.ac.ir/login"
